# NOTA: En producción usar Sealed Secrets o External Secrets Operator.
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: crm-saas
type: Opaque
stringData:
  admin-password: CHANGE_ME_IN_PRODUCTION
