apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-backend-ingress
  namespace: crm-saas
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: crm-backend
                port:
                  number: 8081
