apiVersion: v1
kind: Service
metadata:
  name: crm-backend
  namespace: crm-saas
  labels:
    app: crm-backend
spec:
  selector:
    app: crm-backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
