apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-frontend-ingress
  namespace: crm-saas
  annotations:
    kubernetes.io/ingress.class: traefik
    # Sin TLS para acceso local por HTTP puerto 80
    # igual que viaja-con-moni
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-frontend
                port:
                  number: 3000
