apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm-multitenant
  namespace: argocd
  labels:
    dt.mz: CRM-SaaS
spec:
  project: default

  source:
    repoURL: https://github.com/MAtucR/crm-multitenant.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true        # SIN ESTO ArgoCD solo lee la raiz de k8s/ y no entra en subdirectorios
      exclude: 'argocd/**' # Excluir este mismo archivo para evitar loop

  destination:
    server: https://kubernetes.default.svc
    namespace: crm-saas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
